<a href="https://colab.research.google.com/github/neel786/ML-DL/blob/main/6_K_fold_CV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Use iris flower dataset from sklearn library and use cross_val_score against following models to measure the performance of each. In the end figure out the model with best performance,

Logistic Regression
SVM
Decision Tree
Random Forest

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [2]:
# Load Iris dataset
iris = load_iris()
X = iris.data  # Features
y = iris.target  # Target labels (Setosa, Versicolor, Virginica)

**Logistic Regression**

In [7]:
l_scores=cross_val_score(LogisticRegression(max_iter=200),X,y,)
l_scores

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [8]:
np.average(l_scores)

0.9733333333333334

**Decision Tree**

In [9]:
d_scores=cross_val_score(DecisionTreeClassifier(),X,y)
d_scores

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [10]:
np.average(d_scores)

0.9666666666666668

**SVM**

In [11]:
s_scores=cross_val_score(SVC(),X,y)
s_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [12]:
np.average(s_scores)

0.9666666666666666

**Random Forest**

In [13]:
r_scores=cross_val_score(RandomForestClassifier(n_estimators=40),X,y)
r_scores

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [14]:
np.average(r_scores)

0.9666666666666668